services:
  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: createvagabondapp
    volumes:
      - ./db/data:/var/lib/mysql
