[build]
  publish = "dist/" # relative to base
  framework = "vite"
  targetPort = 5173
  command = "cd ../../ && npm run build"

[functions]
  directory = "../backend/src/functions/" # relative to base

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false
  command = "vite dev"
  targetPort = 5173
  functionsPort = 8788
